### ISSUE TITLE
No memory_bank file in this repository

### ISSUE THREAD

**Issue by WeissTsang** [ChongjianGE/SNCLR#1]
Hi,
    Sorry to interrupt you. There is no memory_bank file or module in the snclr directory. Would it be possible that you've forgotten to upload this file?
Thanks!

**Comment by anishacharya** [comment]
Yes ... This code is not going to run --- The code is mostly modified from lightly NNCLR ~ However, they changed the signature of the memory bank ---- so this code is not going to run ....

**Comment by ChongjianGE** [comment]
Hey guys, sorry for the late reply and missing files. I have just update the memory_bank.py file. Please have a try.

**Comment by ChongjianGE** [comment]
Please feel free to open the issue if there are any further questions.
